### ISSUE TITLE
想问下怎么做返回的响应数据类型校验

### ISSUE THREAD

**Issue by xianjianlf2** [easychen/flowdeer-dist#1]
大佬好，我在用您的项目Flow Deer时  有个问题想请教下您
在使用过程中看到对输入的prompt做了限制，但如果出现gpt乱出答案。
在这种情况下，我们应该如何验证返回数据的准确数据类型？是否可以使用type chat进行验证

![image](https://github.com/easychen/flowdeer-dist/assets/53885024/706fd819-45b2-4dec-b6cb-74069a22ea5c)

**Comment by easychen** [comment]
简单检测可以让直接返回json，然后提取json再测试parse以后的key；复杂一点可以把type定义丢过去。

llm本身就是不稳定的，发现数据不对直接重试就行…
